### ISSUE TITLE
error after install

### ISSUE THREAD

**Issue by ajonno** [prashantvc/SpecialCopy#1]
hi prashant, got this error:

![image](https://cloud.githubusercontent.com/assets/3005269/6033326/7722c302-ac68-11e4-952f-bddc182e0d93.png)

Xamarin Studio
Version 5.7 (build 661)

Operating System
Mac OS X 10.10.1

**Comment by prashantvc** [comment]
@ajonno what was the Json data that you were copying?

**Comment by prashantvc** [comment]
Probably pasting the incorrect JSON text
